/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author almei
 */
public class Apresentação extends javax.swing.JFrame {

    /**
     * Creates new form Apresentação
     */
    public Apresentação() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vamoscomecar = new javax.swing.JLabel();
        simulacao = new javax.swing.JLabel();
        ADMIN = new javax.swing.JLabel();
        SAIR = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        vamoscomecar.setBackground(new java.awt.Color(255, 255, 255));
        vamoscomecar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vamoscomecarMouseClicked(evt);
            }
        });
        getContentPane().add(vamoscomecar);
        vamoscomecar.setBounds(80, 350, 280, 90);

        simulacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simulacaoMouseClicked(evt);
            }
        });
        getContentPane().add(simulacao);
        simulacao.setBounds(80, 460, 280, 80);

        ADMIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADMINMouseClicked(evt);
            }
        });
        getContentPane().add(ADMIN);
        ADMIN.setBounds(770, 490, 50, 50);

        SAIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SAIRMouseClicked(evt);
            }
        });
        getContentPane().add(SAIR);
        SAIR.setBounds(780, 20, 40, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/COMPING.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 830, 570);

        setSize(new java.awt.Dimension(830, 572));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SAIRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SAIRMouseClicked
            System.exit(0);
    }//GEN-LAST:event_SAIRMouseClicked

    private void vamoscomecarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vamoscomecarMouseClicked
       VamosComecar start = new VamosComecar();

       start.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_vamoscomecarMouseClicked

    private void simulacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simulacaoMouseClicked
       Simulacao sim = new Simulacao();
       sim.setVisible(true);
       this.dispose();
        
        
    }//GEN-LAST:event_simulacaoMouseClicked

    private void ADMINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADMINMouseClicked
       LOGIN ADM = new LOGIN();
       ADM.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_ADMINMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Apresentação.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Apresentação.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Apresentação.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Apresentação.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Apresentação().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADMIN;
    private javax.swing.JLabel SAIR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel simulacao;
    private javax.swing.JLabel vamoscomecar;
    // End of variables declaration//GEN-END:variables
}
