/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.DAOArmazenamento;
import Model.MArmazenamento;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author almei
 */
public class Armazenamento extends javax.swing.JFrame {

    /**
     * Creates new form Armazenamento
     */
    public Armazenamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_Fab = new javax.swing.JTextField();
        txt_slot = new javax.swing.JTextField();
        txt_consumo = new javax.swing.JTextField();
        txt_preco = new javax.swing.JTextField();
        txt_modelo = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/arrow-back-icon.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(660, 380, 50, 70);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Modelo");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(60, 250, 70, 30);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Fabricante");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(60, 290, 110, 30);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Slot");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(60, 330, 70, 30);

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Consumo");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(60, 370, 110, 30);

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Preço R$");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(60, 410, 100, 30);

        txt_Fab.setBackground(new java.awt.Color(0, 0, 0));
        txt_Fab.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_Fab.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_Fab);
        txt_Fab.setBounds(170, 290, 180, 30);

        txt_slot.setBackground(new java.awt.Color(0, 0, 0));
        txt_slot.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_slot.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_slot);
        txt_slot.setBounds(170, 330, 180, 30);

        txt_consumo.setBackground(new java.awt.Color(0, 0, 0));
        txt_consumo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_consumo.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_consumo);
        txt_consumo.setBounds(170, 370, 180, 30);

        txt_preco.setBackground(new java.awt.Color(0, 0, 0));
        txt_preco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_preco.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_preco);
        txt_preco.setBounds(170, 410, 180, 30);

        txt_modelo.setBackground(new java.awt.Color(0, 0, 0));
        txt_modelo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_modelo.setForeground(new java.awt.Color(255, 255, 255));
        txt_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_modeloActionPerformed(evt);
            }
        });
        getContentPane().add(txt_modelo);
        txt_modelo.setBounds(170, 250, 180, 30);

        btnCadastrar.setBackground(new java.awt.Color(0, 0, 0));
        btnCadastrar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(153, 153, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(370, 390, 140, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/COMPING100.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 830, 570);

        setSize(new java.awt.Dimension(830, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        PainelLevelTec tec = new PainelLevelTec();
        tec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txt_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_modeloActionPerformed

    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked
        MArmazenamento arm=new MArmazenamento();
        DAOArmazenamento daoarm=new DAOArmazenamento();       
        boolean check=true;
        
        
            if(txt_modelo.getText().isEmpty()    || txt_Fab.getText().isEmpty() 
            || txt_slot.getText().isEmpty() || txt_consumo.getText().isEmpty()
            || txt_preco.getText().isEmpty()
            ){
                JOptionPane.showMessageDialog(null,"Por favor, preencha todos os campos corretamente.");
                check=false;
            }


            if(check=true){
                arm.setMODELO(txt_modelo.getText());
                arm.setFABRICANTE(txt_Fab.getText());
                arm.setSLOT(txt_slot.getText());
                arm.setCONSUMO(Integer.parseInt(txt_consumo.getText()));
                arm.setPRECO(Float.parseFloat(txt_preco.getText()));
                
                if(btnCadastrar.getText().equals("Cadastrar")){ 
                    try {
                        daoarm.inserir(arm,"");
                        JOptionPane.showMessageDialog(null,"Armazenamento cadastrado com sucesso!");
                    } catch (SQLException ex) {
                        Logger.getLogger(PlacaMae.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                   esvaziarCampos();
            }
        
    }        
    }                                 
    private void esvaziarCampos(){
        txt_modelo.setText("");
        txt_preco.setText("");
        txt_consumo.setText("");
        txt_slot.setText("");
        txt_Fab.setText("");
    }//GEN-LAST:event_btnCadastrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Armazenamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Armazenamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Armazenamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Armazenamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Armazenamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_Fab;
    private javax.swing.JTextField txt_consumo;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_preco;
    private javax.swing.JTextField txt_slot;
    // End of variables declaration//GEN-END:variables
}
