/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.DAOFonte;
import DAO.DAOPlaca;
import Model.MFonte;
import Model.MPlacaMae;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author almei
 */
public class Fonte extends javax.swing.JFrame {

    /**
     * Creates new form Fonte
     */
    public Fonte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Fab = new javax.swing.JTextField();
        txt_potencia = new javax.swing.JTextField();
        txt_preal = new javax.swing.JTextField();
        txt_cert = new javax.swing.JTextField();
        txt_preco = new javax.swing.JTextField();
        txt_nome = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        OFF = new javax.swing.JButton();
        ON = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        txt_Fab.setBackground(new java.awt.Color(0, 0, 0));
        txt_Fab.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_Fab.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_Fab);
        txt_Fab.setBounds(160, 280, 220, 30);

        txt_potencia.setBackground(new java.awt.Color(0, 0, 0));
        txt_potencia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_potencia.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_potencia);
        txt_potencia.setBounds(160, 320, 220, 30);

        txt_preal.setBackground(new java.awt.Color(153, 153, 255));
        getContentPane().add(txt_preal);
        txt_preal.setBounds(310, 360, 70, 30);

        txt_cert.setBackground(new java.awt.Color(0, 0, 0));
        txt_cert.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_cert.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_cert);
        txt_cert.setBounds(160, 400, 220, 30);

        txt_preco.setBackground(new java.awt.Color(0, 0, 0));
        txt_preco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_preco.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_preco);
        txt_preco.setBounds(160, 440, 220, 30);

        txt_nome.setBackground(new java.awt.Color(0, 0, 0));
        txt_nome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_nome.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_nome);
        txt_nome.setBounds(160, 240, 220, 30);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Potência Real");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 360, 140, 30);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Potência");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 320, 100, 30);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Fabricante");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(30, 280, 100, 30);

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Certificado");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(30, 400, 120, 30);

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Preço");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(30, 440, 70, 30);

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Nome");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(30, 240, 70, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/arrow-back-icon.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(650, 420, 50, 50);

        OFF.setBackground(new java.awt.Color(0, 0, 0));
        OFF.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        OFF.setForeground(new java.awt.Color(255, 51, 51));
        OFF.setText("OFF");
        OFF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OFFMouseClicked(evt);
            }
        });
        getContentPane().add(OFF);
        OFF.setBounds(230, 360, 60, 30);

        ON.setBackground(new java.awt.Color(0, 0, 0));
        ON.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ON.setForeground(new java.awt.Color(102, 255, 102));
        ON.setText("ON");
        ON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ONMouseClicked(evt);
            }
        });
        getContentPane().add(ON);
        ON.setBounds(160, 360, 60, 30);

        btnCadastrar.setBackground(new java.awt.Color(0, 0, 0));
        btnCadastrar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(153, 153, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(400, 420, 130, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/COMPING20.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 830, 570);

        setSize(new java.awt.Dimension(830, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       PainelLevelTec tec = new PainelLevelTec();
       tec.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void ONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ONMouseClicked

        txt_preal.setText("1");
    }//GEN-LAST:event_ONMouseClicked

    private void OFFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OFFMouseClicked
        txt_preal.setText("0");
    }//GEN-LAST:event_OFFMouseClicked

    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked
               MFonte FON=new MFonte();
       DAOFonte daofonte=new DAOFonte();       

        
        boolean check=true;
        
        
            if(txt_nome.getText().isEmpty()    || txt_Fab.getText().isEmpty() 
            || txt_potencia.getText().isEmpty() || txt_preal.getText().isEmpty()
            || txt_cert.getText().isEmpty() || txt_preco.getText().isEmpty() 
            ){
                JOptionPane.showMessageDialog(null,"Por favor, preencha todos os campos corretamente");
                check=false;
            }


            if(check=true){
                FON.setNOME(txt_nome.getText());
                FON.setFABRICANTE(txt_Fab.getText());
                FON.setPOTENCIA(Integer.parseInt(txt_potencia.getText()));
                FON.setPREAL(Boolean.parseBoolean(txt_preal.getText()));
                FON.setCERTIFICADO(txt_cert.getText());
                FON.setPRECO(Float.parseFloat(txt_preco.getText()));

                if(btnCadastrar.getText().equals("Cadastrar")){ 

                    try {
                        daofonte.inserir(FON,"");
                        JOptionPane.showMessageDialog(null,"Fonte cadastrada com sucesso!");
                    } catch (SQLException ex) {
                        Logger.getLogger(PlacaMae.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                   esvaziarCampos();
            }
    }                                         
    
    }//GEN-LAST:event_btnCadastrarMouseClicked

        private void esvaziarCampos(){

        txt_nome.setText("");
        txt_preal.setText("");
        txt_potencia.setText("");
        txt_Fab.setText("");
        txt_preco.setText("");
        txt_cert.setText("");

        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fonte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fonte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fonte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fonte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fonte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OFF;
    private javax.swing.JButton ON;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_Fab;
    private javax.swing.JTextField txt_cert;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_potencia;
    private javax.swing.JTextField txt_preal;
    private javax.swing.JTextField txt_preco;
    // End of variables declaration//GEN-END:variables
}
