/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.DAOPlaca;
import DAO.DAOUsuario;
import Model.MPlacaMae;
import Model.MUsuario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author almei
 */
public class PainelLevelADM extends javax.swing.JFrame {

    /**
     * Creates new form PainelLevelADM
     */
    public PainelLevelADM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_nome = new javax.swing.JTextField();
        txt_tipo = new javax.swing.JTextField();
        txt_cod = new javax.swing.JTextField();
        btn_Cadastrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_senha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);
        getContentPane().add(txt_nome);
        txt_nome.setBounds(200, 290, 350, 30);
        getContentPane().add(txt_tipo);
        txt_tipo.setBounds(200, 410, 350, 30);

        txt_cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codActionPerformed(evt);
            }
        });
        getContentPane().add(txt_cod);
        txt_cod.setBounds(330, 250, 220, 30);

        btn_Cadastrar.setText("Cadastrar");
        btn_Cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CadastrarMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Cadastrar);
        btn_Cadastrar.setBounds(440, 460, 110, 40);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome*");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 290, 100, 40);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Senha*");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 330, 90, 40);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 410, 49, 40);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Código de Acesso*");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 240, 250, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/arrow-back-icon.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(750, 470, 50, 50);
        getContentPane().add(txt_senha);
        txt_senha.setBounds(201, 330, 350, 30);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("E-mail*");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 370, 83, 40);
        getContentPane().add(txt_email);
        txt_email.setBounds(200, 370, 350, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/COMPING5.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 840, 590);

        setSize(new java.awt.Dimension(830, 569));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
       Apresentação ap = new Apresentação();
       ap.setVisible(true);
       this.dispose();
  
    }//GEN-LAST:event_jLabel7MouseClicked

    
    
    private void esvaziarCampos(){

        txt_cod.setText("");
        txt_nome.setText("");
        txt_email.setText("");
        txt_senha.setText("");
        txt_tipo.setText("");
    }
    private void btn_CadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CadastrarMouseClicked
        // TODO add your handling code here:
        
        MUsuario usuario=new MUsuario();
        DAOUsuario daouser=new DAOUsuario();       

        
        boolean check=true;
        
        
            if(txt_cod.getText().isEmpty()    || txt_nome.getText().isEmpty() 
            || txt_senha.getText().isEmpty() || txt_tipo.getText().isEmpty() || txt_email.getText().isEmpty()
            )
            {
                JOptionPane.showMessageDialog(null,"Por favor, preencha todos os campos corretamente");
                check=false;
            }


            if(check=true){
                usuario.setCODIGO(txt_cod.getText());
                usuario.setNOME(txt_nome.getText());
                usuario.setSENHA(txt_senha.getText());
                usuario.setEMAIL(txt_email.getText());
                usuario.setTIPO(txt_tipo.getText());
 

                if(btn_Cadastrar.getText().equals("Cadastrar")){ 
                    try {
                        daouser.inserir(usuario,"");
                       JOptionPane.showMessageDialog(null,"Cadastro de novo membro efetuado com sucesso!");
                    } catch (SQLException ex) {
                        Logger.getLogger(PainelLevelADM.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    esvaziarCampos();
            }
    }               
    }//GEN-LAST:event_btn_CadastrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainelLevelADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainelLevelADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainelLevelADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainelLevelADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PainelLevelADM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt_cod;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JPasswordField txt_senha;
    private javax.swing.JTextField txt_tipo;
    // End of variables declaration//GEN-END:variables
}
