/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author almei
 */
public class PainelLevelTec extends javax.swing.JFrame {

    /**
     * Creates new form PainelLevelTec
     */
    public PainelLevelTec() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_processador = new javax.swing.JButton();
        btn_memoriaram = new javax.swing.JButton();
        btn_armazenamento = new javax.swing.JButton();
        btn_placadevideo = new javax.swing.JButton();
        btn_fonte = new javax.swing.JButton();
        btn_placa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(854, 0, 0, 581);

        btn_processador.setBackground(new java.awt.Color(0, 0, 0));
        btn_processador.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btn_processador.setForeground(new java.awt.Color(153, 153, 255));
        btn_processador.setText("PROCESSADOR");
        btn_processador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_processadorMouseClicked(evt);
            }
        });
        btn_processador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_processadorActionPerformed(evt);
            }
        });
        getContentPane().add(btn_processador);
        btn_processador.setBounds(90, 280, 210, 50);

        btn_memoriaram.setBackground(new java.awt.Color(0, 0, 0));
        btn_memoriaram.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btn_memoriaram.setForeground(new java.awt.Color(153, 153, 255));
        btn_memoriaram.setText("MEMÓRIA RAM");
        btn_memoriaram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_memoriaramMouseClicked(evt);
            }
        });
        btn_memoriaram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_memoriaramActionPerformed(evt);
            }
        });
        getContentPane().add(btn_memoriaram);
        btn_memoriaram.setBounds(530, 370, 220, 50);

        btn_armazenamento.setBackground(new java.awt.Color(0, 0, 0));
        btn_armazenamento.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btn_armazenamento.setForeground(new java.awt.Color(153, 153, 255));
        btn_armazenamento.setText("ARMAZENAMENTO");
        btn_armazenamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_armazenamentoMouseClicked(evt);
            }
        });
        btn_armazenamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_armazenamentoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_armazenamento);
        btn_armazenamento.setBounds(530, 180, 220, 50);

        btn_placadevideo.setBackground(new java.awt.Color(0, 0, 0));
        btn_placadevideo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btn_placadevideo.setForeground(new java.awt.Color(153, 153, 255));
        btn_placadevideo.setText("PLACA DE VÍDEO");
        btn_placadevideo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_placadevideoMouseClicked(evt);
            }
        });
        btn_placadevideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_placadevideoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_placadevideo);
        btn_placadevideo.setBounds(530, 280, 220, 50);

        btn_fonte.setBackground(new java.awt.Color(0, 0, 0));
        btn_fonte.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btn_fonte.setForeground(new java.awt.Color(153, 153, 255));
        btn_fonte.setText("FONTE");
        btn_fonte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_fonteMouseClicked(evt);
            }
        });
        btn_fonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fonteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_fonte);
        btn_fonte.setBounds(90, 370, 210, 50);

        btn_placa.setBackground(new java.awt.Color(0, 0, 0));
        btn_placa.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btn_placa.setForeground(new java.awt.Color(153, 153, 255));
        btn_placa.setText("PLACA-MÃE");
        btn_placa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_placaMouseClicked(evt);
            }
        });
        btn_placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_placaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_placa);
        btn_placa.setBounds(90, 180, 210, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/aaaaaaaaa.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 480, 160, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/COMPING6.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 826, 570);

        setSize(new java.awt.Dimension(830, 573));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_processadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_processadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_processadorActionPerformed

    private void btn_memoriaramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_memoriaramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_memoriaramActionPerformed

    private void btn_armazenamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_armazenamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_armazenamentoActionPerformed

    private void btn_placadevideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_placadevideoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_placadevideoActionPerformed

    private void btn_fonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fonteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_fonteActionPerformed

    private void btn_placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_placaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_placaActionPerformed

    private void btn_placaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_placaMouseClicked
        PlacaMae pl = new PlacaMae();
        pl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_placaMouseClicked

    private void btn_processadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_processadorMouseClicked
        Processador pro = new Processador();
        pro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_processadorMouseClicked

    private void btn_fonteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_fonteMouseClicked
        Fonte f = new Fonte();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_fonteMouseClicked

    private void btn_armazenamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_armazenamentoMouseClicked
        Armazenamento arm = new Armazenamento();
        arm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_armazenamentoMouseClicked

    private void btn_placadevideoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_placadevideoMouseClicked
        PlacaVideo pv = new PlacaVideo();
        pv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_placadevideoMouseClicked

    private void btn_memoriaramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_memoriaramMouseClicked
        MemoriaRAM mem = new MemoriaRAM();
        mem.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_memoriaramMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Apresentação ap = new Apresentação();
        ap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainelLevelTec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainelLevelTec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainelLevelTec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainelLevelTec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PainelLevelTec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_armazenamento;
    private javax.swing.JButton btn_fonte;
    private javax.swing.JButton btn_memoriaram;
    private javax.swing.JButton btn_placa;
    private javax.swing.JButton btn_placadevideo;
    private javax.swing.JButton btn_processador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
