/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.DAOMemoria;
import DAO.DAOPlacavideo;
import Model.MMemoria;
import Model.MPlacavideo;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author almei
 */
public class PlacaVideo extends javax.swing.JFrame {

    /**
     * Creates new form PlacaVideo
     */
    public PlacaVideo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_Fab = new javax.swing.JTextField();
        txt_mem = new javax.swing.JTextField();
        txt_banda = new javax.swing.JTextField();
        txt_vermem = new javax.swing.JTextField();
        txt_preco = new javax.swing.JTextField();
        txt_nome = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/arrow-back-icon.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(660, 390, 50, 50);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Fabricante");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(40, 240, 100, 30);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Mem (Qtde.)");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(40, 280, 120, 30);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Banda");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(40, 320, 70, 30);

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("VERMEM");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(40, 360, 90, 30);

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Preço");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(40, 400, 70, 30);

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Nome");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(40, 200, 70, 30);
        getContentPane().add(txt_Fab);
        txt_Fab.setBounds(140, 240, 250, 30);
        getContentPane().add(txt_mem);
        txt_mem.setBounds(170, 280, 220, 30);
        getContentPane().add(txt_banda);
        txt_banda.setBounds(150, 320, 240, 30);
        getContentPane().add(txt_vermem);
        txt_vermem.setBounds(130, 360, 260, 30);
        getContentPane().add(txt_preco);
        txt_preco.setBounds(130, 400, 260, 30);
        getContentPane().add(txt_nome);
        txt_nome.setBounds(140, 200, 250, 30);

        btnCadastrar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(410, 390, 120, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/COMPING1000.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 830, 570);

        setSize(new java.awt.Dimension(830, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       PainelLevelTec tec = new PainelLevelTec();
       tec.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked
        MPlacavideo vid=new MPlacavideo();
        DAOPlacavideo daovid=new DAOPlacavideo();       

        
        boolean check=true;
        
        
            if(txt_nome.getText().isEmpty()    || txt_Fab.getText().isEmpty() 
            || txt_mem.getText().isEmpty() || txt_banda.getText().isEmpty()
            || txt_preco.getText().isEmpty() || txt_vermem.getText().isEmpty() 
            ){
                JOptionPane.showMessageDialog(null,"Por favor, preencha todos os campos corretamente");
                check=false;
            }


            if(check=true){
                vid.setNOME(txt_nome.getText());
                vid.setFABRICANTE(txt_Fab.getText());
                vid.setQTDMEM(Integer.parseInt(txt_mem.getText()));
                vid.setBANDA(Integer.parseInt(txt_banda.getText()));
                vid.setVERMEM(txt_vermem.getText());
                vid.setPRECO(Float.parseFloat(txt_preco.getText()));
                if(btnCadastrar.getText().equals("Cadastrar")){ 
                    try {
                        daovid.inserir(vid,"");
                        JOptionPane.showMessageDialog(null,"Placa de vídeo cadastrada com sucesso!");
                    } catch (SQLException ex) {
                        Logger.getLogger(PlacaMae.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                   esvaziarCampos();
            }
    }     
                                              

    }//GEN-LAST:event_btnCadastrarMouseClicked
    private void esvaziarCampos(){
        
    
        txt_banda.setText("");
        txt_nome.setText("");
        txt_mem.setText("");
        txt_preco.setText("");
        txt_Fab.setText("");
        txt_vermem.setText("");

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlacaVideo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlacaVideo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlacaVideo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlacaVideo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlacaVideo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_Fab;
    private javax.swing.JTextField txt_banda;
    private javax.swing.JTextField txt_mem;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_preco;
    private javax.swing.JTextField txt_vermem;
    // End of variables declaration//GEN-END:variables
}
