/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import DAO.DAOPlaca;
import Model.MPlacaMae;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author almei
 */
public class PlacaMae extends javax.swing.JFrame {
   // DAOPlaca daoplaca=new DAOPlaca();       
    //MPlacaMae mplacamae=new MPlacaMae();

 //   daoplaca = DAO.buscar();
  //  DAO.delete(daoplaca);
   // DAOPlaca.inserir(daoplaca);
    List<MPlacaMae> placas;
    /**
     * Creates new form PlacaMae
     */
    public PlacaMae() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_nome = new javax.swing.JTextField();
        txt_Fab = new javax.swing.JTextField();
        txt_socket = new javax.swing.JTextField();
        txt_tiposata = new javax.swing.JTextField();
        txt_qtdsata = new javax.swing.JTextField();
        txt_vermem = new javax.swing.JTextField();
        txt_fmem = new javax.swing.JTextField();
        txt_memax = new javax.swing.JTextField();
        txt_qtdpci = new javax.swing.JTextField();
        txt_m2 = new javax.swing.JTextField();
        txt_ide = new javax.swing.JTextField();
        txt_preco = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JLABELA = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dsdas = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        txt_nome.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(txt_nome);
        txt_nome.setBounds(130, 200, 220, 20);

        txt_Fab.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(txt_Fab);
        txt_Fab.setBounds(130, 230, 220, 19);
        getContentPane().add(txt_socket);
        txt_socket.setBounds(130, 260, 220, 20);
        getContentPane().add(txt_tiposata);
        txt_tiposata.setBounds(130, 290, 220, 20);
        getContentPane().add(txt_qtdsata);
        txt_qtdsata.setBounds(130, 320, 220, 20);
        getContentPane().add(txt_vermem);
        txt_vermem.setBounds(130, 350, 220, 20);
        getContentPane().add(txt_fmem);
        txt_fmem.setBounds(130, 380, 220, 20);
        getContentPane().add(txt_memax);
        txt_memax.setBounds(130, 410, 220, 20);
        getContentPane().add(txt_qtdpci);
        txt_qtdpci.setBounds(130, 440, 220, 20);

        txt_m2.setBackground(new java.awt.Color(153, 153, 255));
        getContentPane().add(txt_m2);
        txt_m2.setBounds(270, 470, 80, 20);

        txt_ide.setBackground(new java.awt.Color(153, 153, 255));
        getContentPane().add(txt_ide);
        txt_ide.setBounds(270, 500, 80, 20);
        getContentPane().add(txt_preco);
        txt_preco.setBounds(130, 530, 220, 20);

        btnCadastrar.setBackground(new java.awt.Color(0, 0, 0));
        btnCadastrar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(102, 102, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(380, 490, 140, 60);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fabricante");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 220, 140, 30);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Socket");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 250, 70, 30);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sata (Tipo)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 280, 100, 30);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sata(Qtde.)");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 310, 110, 30);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("VERMEM");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 340, 100, 30);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("FMEM");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 370, 70, 30);

        JLABELA.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        JLABELA.setForeground(new java.awt.Color(255, 255, 255));
        JLABELA.setText("MEMAX");
        getContentPane().add(JLABELA);
        JLABELA.setBounds(30, 400, 70, 30);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PCI (Qtde.)");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 430, 110, 30);

        dsdas.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        dsdas.setForeground(new java.awt.Color(255, 255, 255));
        dsdas.setText("M2");
        getContentPane().add(dsdas);
        dsdas.setBounds(30, 460, 70, 30);

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("IDE");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 490, 70, 30);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Preço");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 520, 70, 30);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nome");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 190, 70, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/arrow-back-icon.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(630, 480, 50, 60);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("OFF");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 470, 60, 23);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 255, 102));
        jButton2.setText("ON");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(130, 470, 50, 23);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 255, 102));
        jButton3.setText("ON");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(130, 500, 50, 23);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 0, 51));
        jButton4.setText("OFF");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(190, 500, 60, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/COMPING7.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 830, 570);

        setSize(new java.awt.Dimension(830, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void esvaziarCampos(){

        txt_socket.setText("");
        txt_nome.setText("");
        txt_qtdsata.setText("");
        txt_fmem.setText("");
        txt_qtdpci.setText("");
        txt_preco.setText("");
        txt_tiposata.setText("");
        txt_vermem.setText("");
        txt_ide.setText("");
        txt_Fab.setText("");
         txt_m2.setText("");
        txt_memax.setText("");
        
    }
    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked
        MPlacaMae placa=new MPlacaMae();
        DAOPlaca daoplaca=new DAOPlaca();       

        
        boolean check=true;
        
        
            if(txt_nome.getText().isEmpty()    || txt_Fab.getText().isEmpty() 
            || txt_socket.getText().isEmpty() || txt_tiposata.getText().isEmpty()
            || txt_qtdsata.getText().isEmpty() || txt_vermem.getText().isEmpty() 
            || txt_fmem.getText().isEmpty()    || txt_memax.getText().isEmpty()
            || txt_qtdpci.getText().isEmpty()  || txt_m2.getText().isEmpty()
            || txt_ide.getText().isEmpty()     || txt_preco.getText().isEmpty()
            ){
                JOptionPane.showMessageDialog(null,"Por favor, preencha todos os campos corretamente");
                check=false;
            }


            if(check=true){
                placa.setNOME(txt_nome.getText());
                placa.setFABRICANTE(txt_Fab.getText());
                placa.setSOCKET(txt_socket.getText());
                placa.setTIPOSATA(txt_tiposata.getText());
                placa.setQTDSATA(Integer.parseInt(txt_qtdsata.getText()));
                placa.setVERMEM(txt_vermem.getText());
                placa.setFMEM(Integer.parseInt(txt_fmem.getText()));
                placa.setMEMAX(Integer.parseInt(txt_memax.getText()));
                placa.setQTDPCI(Integer.parseInt(txt_qtdpci.getText()));
                placa.setM2(Boolean.parseBoolean(txt_m2.getText()));
                placa.setIDE(Boolean.parseBoolean(txt_ide.getText()));
                placa.setPRECO(Float.parseFloat(txt_preco.getText()));

                if(btnCadastrar.getText().equals("Cadastrar")){ 

                    try {
                        daoplaca.inserir(placa,"");
                        JOptionPane.showMessageDialog(null,"Placa Mãe cadastrada com sucesso!");
                    } catch (SQLException ex) {
                        Logger.getLogger(PlacaMae.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                   esvaziarCampos();
            }
    }//GEN-LAST:event_btnCadastrarMouseClicked
    }
    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        PainelLevelTec tec = new PainelLevelTec();
        tec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
       txt_m2.setText("1");
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
              txt_m2.setText("0");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        txt_ide.setText("1");
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
      txt_ide.setText("0");

    }//GEN-LAST:event_jButton4MouseClicked
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlacaMae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlacaMae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlacaMae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlacaMae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlacaMae().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLABELA;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel dsdas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_Fab;
    private javax.swing.JTextField txt_fmem;
    private javax.swing.JTextField txt_ide;
    private javax.swing.JTextField txt_m2;
    private javax.swing.JTextField txt_memax;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_preco;
    private javax.swing.JTextField txt_qtdpci;
    private javax.swing.JTextField txt_qtdsata;
    private javax.swing.JTextField txt_socket;
    private javax.swing.JTextField txt_tiposata;
    private javax.swing.JTextField txt_vermem;
    // End of variables declaration//GEN-END:variables
}
