/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.DAOPlaca;
import DAO.DAOProcessador;
import Model.MPlacaMae;
import Model.MProcessador;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author almei
 */
public class Processador extends javax.swing.JFrame {

    /**
     * Creates new form Processador
     */
    public Processador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Fab = new javax.swing.JTextField();
        txt_socket = new javax.swing.JTextField();
        txt_frequencia = new javax.swing.JTextField();
        txt_cache = new javax.swing.JTextField();
        txt_consumo = new javax.swing.JTextField();
        txt_preco = new javax.swing.JTextField();
        txt_nome = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        CSDDFDS = new javax.swing.JLabel();
        csfdsf = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);
        getContentPane().add(txt_Fab);
        txt_Fab.setBounds(140, 240, 240, 30);
        getContentPane().add(txt_socket);
        txt_socket.setBounds(140, 280, 240, 30);
        getContentPane().add(txt_frequencia);
        txt_frequencia.setBounds(140, 320, 240, 30);
        getContentPane().add(txt_cache);
        txt_cache.setBounds(140, 360, 240, 30);
        getContentPane().add(txt_consumo);
        txt_consumo.setBounds(140, 400, 240, 30);
        getContentPane().add(txt_preco);
        txt_preco.setBounds(140, 440, 240, 30);
        getContentPane().add(txt_nome);
        txt_nome.setBounds(140, 200, 240, 30);

        btnCadastrar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(400, 420, 130, 50);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Fabricante");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 240, 140, 30);

        CSDDFDS.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        CSDDFDS.setForeground(new java.awt.Color(255, 255, 255));
        CSDDFDS.setText("SOCKET");
        getContentPane().add(CSDDFDS);
        CSDDFDS.setBounds(30, 280, 70, 30);

        csfdsf.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        csfdsf.setForeground(new java.awt.Color(255, 255, 255));
        csfdsf.setText("Frequência");
        getContentPane().add(csfdsf);
        csfdsf.setBounds(30, 320, 110, 30);

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("CACHE");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(30, 360, 70, 30);

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Consumo");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(30, 400, 90, 30);

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Preço");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(30, 440, 70, 30);

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Nome");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(30, 200, 60, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/arrow-back-icon.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(660, 410, 60, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/COMPING8.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 868, 570);

        setSize(new java.awt.Dimension(830, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        PainelLevelTec tec = new PainelLevelTec();
        tec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked
    private void esvaziarCampos(){

        txt_socket.setText("");
        txt_nome.setText("");
        txt_cache.setText("");
        txt_frequencia.setText("");
        txt_preco.setText("");
        txt_Fab.setText("");
        txt_consumo.setText("");
        
    }
    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked
        MProcessador pro=new MProcessador();
        DAOProcessador daopro=new DAOProcessador();       

        boolean check=true;
        
            if(txt_nome.getText().isEmpty()    || txt_Fab.getText().isEmpty() 
            || txt_socket.getText().isEmpty() || txt_frequencia.getText().isEmpty()
            || txt_cache.getText().isEmpty() || txt_consumo.getText().isEmpty() 
            || txt_preco.getText().isEmpty()
            ){
                JOptionPane.showMessageDialog(null,"Por favor, preencha todos os campos corretamente");
                check=false;
            }

            if(check=true){
                pro.setNOME(txt_nome.getText());
                pro.setFABRICANTE(txt_Fab.getText());
                pro.setSOCKET(txt_socket.getText());
                pro.setFREQUENCIA(Integer.parseInt(txt_frequencia.getText()));
                pro.setCACHE(Integer.parseInt(txt_cache.getText()));
                pro.setCONSUMO(Integer.parseInt(txt_consumo.getText()));
                pro.setPRECO(Float.parseFloat(txt_preco.getText()));

                if(btnCadastrar.getText().equals("Cadastrar")){ 

                    try {
                        daopro.inserir(pro,"");
                         JOptionPane.showMessageDialog(null,"Dados cadastrados com sucesso.");
                    } catch (SQLException ex) {
                        Logger.getLogger(Processador.class.getName()).log(Level.SEVERE, null, ex);
                    }    
            }
                esvaziarCampos();
    }                                         
    }//GEN-LAST:event_btnCadastrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Processador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Processador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Processador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Processador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Processador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CSDDFDS;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel csfdsf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JTextField txt_Fab;
    private javax.swing.JTextField txt_cache;
    private javax.swing.JTextField txt_consumo;
    private javax.swing.JTextField txt_frequencia;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_preco;
    private javax.swing.JTextField txt_socket;
    // End of variables declaration//GEN-END:variables
}
