
package View;

import DAO.DAOArmazenamento;
import DAO.DAOFonte;
import DAO.DAOMemoria;
import DAO.DAOPlaca;
import DAO.DAOPlacavideo;
import DAO.DAOProcessador;
import Model.MArmazenamento;
import Model.MFonte;
import Model.MMemoria;
import Model.MPlacaMae;
import Model.MPlacavideo;
import Model.MProcessador;

import java.sql.SQLException;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;


public class Simulacao extends javax.swing.JFrame {
  
       DAOPlaca daoplaca = new DAOPlaca();
       DefaultComboBoxModel pl;
       DAOProcessador daoprocessador = new DAOProcessador();
       DAOMemoria daomemoria = new DAOMemoria();
       DAOArmazenamento daoarmazenamento = new DAOArmazenamento();
       DAOFonte daofonte = new DAOFonte();
       DAOPlacavideo daoplacavideo = new DAOPlacavideo();
    /**
     * Creates new form Simulacao
     */
    public Simulacao() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        c3 = new javax.swing.JLabel();
        c4 = new javax.swing.JLabel();
        c6 = new javax.swing.JLabel();
        c5 = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();
        c1 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        cb_pv = new javax.swing.JComboBox<>();
        cb_arm = new javax.swing.JComboBox<>();
        cb_mem = new javax.swing.JComboBox<>();
        cb_process = new javax.swing.JComboBox<>();
        cb_placa = new javax.swing.JComboBox<>();
        cb_fonte = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btn_desfaz = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        c3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        c3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(c3);
        c3.setBounds(360, 230, 420, 40);

        c4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        c4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(c4);
        c4.setBounds(360, 290, 430, 40);

        c6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        c6.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(c6);
        c6.setBounds(360, 410, 430, 40);

        c5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        c5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(c5);
        c5.setBounds(360, 350, 410, 40);

        c2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        c2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(c2);
        c2.setBounds(360, 170, 420, 40);

        c1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        c1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(c1);
        c1.setBounds(360, 100, 400, 40);

        l1.setBackground(new java.awt.Color(0, 0, 0));
        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cats.jpg"))); // NOI18N
        getContentPane().add(l1);
        l1.setBounds(330, 90, 430, 400);

        cb_pv.setBackground(new java.awt.Color(153, 153, 255));
        cb_pv.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cb_pv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_pvActionPerformed(evt);
            }
        });
        getContentPane().add(cb_pv);
        cb_pv.setBounds(330, 340, 390, 40);

        cb_arm.setBackground(new java.awt.Color(153, 153, 255));
        cb_arm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cb_arm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_armActionPerformed(evt);
            }
        });
        getContentPane().add(cb_arm);
        cb_arm.setBounds(330, 280, 390, 40);

        cb_mem.setBackground(new java.awt.Color(153, 153, 255));
        cb_mem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cb_mem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_memActionPerformed(evt);
            }
        });
        getContentPane().add(cb_mem);
        cb_mem.setBounds(330, 220, 390, 40);

        cb_process.setBackground(new java.awt.Color(153, 153, 255));
        cb_process.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cb_process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_processActionPerformed(evt);
            }
        });
        getContentPane().add(cb_process);
        cb_process.setBounds(330, 160, 390, 40);

        cb_placa.setBackground(new java.awt.Color(153, 153, 255));
        cb_placa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cb_placa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_placaMouseClicked(evt);
            }
        });
        cb_placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_placaActionPerformed(evt);
            }
        });
        getContentPane().add(cb_placa);
        cb_placa.setBounds(330, 100, 390, 40);

        cb_fonte.setBackground(new java.awt.Color(153, 153, 255));
        cb_fonte.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cb_fonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_fonteActionPerformed(evt);
            }
        });
        getContentPane().add(cb_fonte);
        cb_fonte.setBounds(330, 400, 390, 40);

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setText("VER SIMULAÇÃO");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 500, 180, 50);

        btn_desfaz.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_desfaz.setText("DESFAZER TUDO");
        btn_desfaz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_desfazMouseClicked(evt);
            }
        });
        btn_desfaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desfazActionPerformed(evt);
            }
        });
        getContentPane().add(btn_desfaz);
        btn_desfaz.setBounds(630, 500, 150, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/arrow-back-icon.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 490, 60, 60);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("PROCESSADOR");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(130, 170, 180, 30);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("MEMÓRIA RAM");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(120, 230, 180, 30);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("ARMAZENAMENTO");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(80, 290, 220, 30);

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("PLACA DE VÍDEO");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(100, 350, 195, 30);

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("FONTE DE ALIMEN.");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(90, 410, 210, 30);

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("PLACA MÃE");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(150, 110, 180, 30);

        btn2.setBackground(new java.awt.Color(0, 0, 0));
        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/checkmark-4 (1).png"))); // NOI18N
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
        });
        getContentPane().add(btn2);
        btn2.setBounds(730, 160, 81, 40);

        btn3.setBackground(new java.awt.Color(0, 0, 0));
        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/checkmark-4 (1).png"))); // NOI18N
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3MouseClicked(evt);
            }
        });
        getContentPane().add(btn3);
        btn3.setBounds(730, 220, 81, 40);

        btn4.setBackground(new java.awt.Color(0, 0, 0));
        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/checkmark-4 (1).png"))); // NOI18N
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn4MouseClicked(evt);
            }
        });
        getContentPane().add(btn4);
        btn4.setBounds(730, 280, 81, 40);

        btn5.setBackground(new java.awt.Color(0, 0, 0));
        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/checkmark-4 (1).png"))); // NOI18N
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn5MouseClicked(evt);
            }
        });
        getContentPane().add(btn5);
        btn5.setBounds(730, 340, 81, 40);

        btn6.setBackground(new java.awt.Color(0, 0, 0));
        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/checkmark-4 (1).png"))); // NOI18N
        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn6MouseClicked(evt);
            }
        });
        getContentPane().add(btn6);
        btn6.setBounds(730, 400, 81, 40);

        btn1.setBackground(new java.awt.Color(0, 0, 0));
        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/checkmark-4 (1).png"))); // NOI18N
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
        });
        getContentPane().add(btn1);
        btn1.setBounds(730, 100, 81, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/COMPATISIM.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 831, 570);

        setSize(new java.awt.Dimension(830, 576));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cb_pvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_pvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_pvActionPerformed

    private void cb_armActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_armActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_armActionPerformed

    private void cb_memActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_memActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_memActionPerformed

    private void cb_processActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_processActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_processActionPerformed

    private void cb_placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_placaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_placaActionPerformed

    private void cb_fonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_fonteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_fonteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_desfazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desfazActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_desfazActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
           Apresentação ap = new Apresentação();
           ap.setVisible(true);
           this.dispose();
           
    }//GEN-LAST:event_jLabel2MouseClicked


    private void cb_placaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_placaMouseClicked

    }//GEN-LAST:event_cb_placaMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        l1.setVisible(false);
        c1.setVisible(false);
        c2.setVisible(false);
        c3.setVisible(false);
        c4.setVisible(false);
        c5.setVisible(false);
        c6.setVisible(false);
        
           try {
             for(MPlacaMae p: daoplaca.listar("")){
                 
                 cb_placa.addItem(p);
            }
           } catch (SQLException ex) {
               Logger.getLogger(Simulacao.class.getName()).log(Level.SEVERE, null, ex);
           }
        
       
//---------------------------------------------------------------------------------------------
     /*      try {
               //
               MPlacaMae OBJ = new MPlacaMae();
               OBJ.setNOME(cb_placa.getSelectedItem().toString());
               OBJ = daoplaca.buscar(OBJ,"");
              //
              
              
             for(MProcessador r: daoprocessador.listar("SELECT * FROM processador WHERE socket ="+OBJ.getSOCKET())){
                 cb_process.addItem(r);
            }
           } catch (SQLException ex) {
               Logger.getLogger(Simulacao.class.getName()).log(Level.SEVERE, null, ex);
           }*/
//--------------------------------------------------------------------------------------------- 
     /*       try {
             for(MMemoria m: daomemoria.listar("")){
                 cb_mem.addItem(m);
            }
           } catch (SQLException ex) {
               Logger.getLogger(Simulacao.class.getName()).log(Level.SEVERE, null, ex);
           }  */
//--------------------------------------------------------------------------------------------- 
       /*     try {
             for(MArmazenamento a: daoarmazenamento.listar("")){
                 cb_arm.addItem(a);
            }
           } catch (SQLException ex) {
               Logger.getLogger(Simulacao.class.getName()).log(Level.SEVERE, null, ex);
           }  */
//--------------------------------------------------------------------------------------------- 
     /*       try {
             for(MPlacavideo v: daoplacavideo.listar("")){
                 cb_pv.addItem(v);
            }
           } catch (SQLException ex) {
               Logger.getLogger(Simulacao.class.getName()).log(Level.SEVERE, null, ex);
           }  */
 //---------------------------------------------------------------------------------------------            
     /*      try {
             for(MFonte ff: daofonte.listar("")){
                 cb_fonte.addItem(ff);
            }
           } catch (SQLException ex) {
               Logger.getLogger(Simulacao.class.getName()).log(Level.SEVERE, null, ex);
           } */
  //---------------------------------------------------------------------------------------------           
          cb_process.setEnabled(false);
          cb_mem.setEnabled(false);
          cb_fonte.setEnabled(false);
          cb_arm.setEnabled(false);
          cb_pv.setEnabled(false);
          
    }//GEN-LAST:event_formWindowOpened

    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
          cb_process.setEnabled(true);
          cb_placa.setEnabled(false);
          btn1.setEnabled(false);
          
          
               try {
               //
               MPlacaMae OBJ = new MPlacaMae();
               OBJ.setNOME(cb_placa.getSelectedItem().toString());
               OBJ = daoplaca.buscar(OBJ,"");
              //
              
              
             for(MProcessador r: daoprocessador.listar("SELECT * FROM processador WHERE socket='"+OBJ.getSOCKET()+"'")){
                 cb_process.addItem(r);
            }
           } catch (SQLException ex) {
               Logger.getLogger(Simulacao.class.getName()).log(Level.SEVERE, null, ex);
           }
    }//GEN-LAST:event_btn1MouseClicked

    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseClicked
             try {
             for(MMemoria m: daomemoria.listar("")){
                 cb_mem.addItem(m);
            }
           } catch (SQLException ex) {
               Logger.getLogger(Simulacao.class.getName()).log(Level.SEVERE, null, ex);
           } 
        
        
        cb_mem.setEnabled(true);  
          cb_process.setEnabled(false);
          btn2.setEnabled(false);
    }//GEN-LAST:event_btn2MouseClicked

    private void btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseClicked
        
        cb_arm.setEnabled(true); 
        cb_mem.setEnabled(false);
        btn3.setEnabled(false);
        
          try {
             for(MArmazenamento a: daoarmazenamento.listar("")){
                 cb_arm.addItem(a);
            }
           } catch (SQLException ex) {
               Logger.getLogger(Simulacao.class.getName()).log(Level.SEVERE, null, ex);
           } 
    }//GEN-LAST:event_btn3MouseClicked

    private void btn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseClicked
         try {
             for(MPlacavideo v: daoplacavideo.listar("")){
                 cb_pv.addItem(v);
            }
           } catch (SQLException ex) {
               Logger.getLogger(Simulacao.class.getName()).log(Level.SEVERE, null, ex);
           } 
        cb_pv.setEnabled(true); 
        cb_arm.setEnabled(false);
        btn4.setEnabled(false);
    }//GEN-LAST:event_btn4MouseClicked

    private void btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseClicked
        cb_fonte.setEnabled(false); 
       btn6.setEnabled(false);
    }//GEN-LAST:event_btn6MouseClicked

    private void btn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseClicked
            try {
             for(MFonte ff: daofonte.listar("")){
                 cb_fonte.addItem(ff);
            }
           } catch (SQLException ex) {
               Logger.getLogger(Simulacao.class.getName()).log(Level.SEVERE, null, ex);
           } 
        
        cb_fonte.setEnabled(true); 
        cb_pv.setEnabled(false);
       btn5.setEnabled(false);
    }//GEN-LAST:event_btn5MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       
         l1.setVisible(true);
         c1.setVisible(true);
        c2.setVisible(true);
        c3.setVisible(true);
        c4.setVisible(true);
        c5.setVisible(true);
        c6.setVisible(true);
        String a =  cb_placa.getSelectedItem().toString();
        String b = cb_process.getSelectedItem().toString();
        String c = cb_mem.getSelectedItem().toString();
        String d = cb_arm.getSelectedItem().toString();
        String e = cb_pv.getSelectedItem().toString();
        String f = cb_fonte.getSelectedItem().toString();
        c1.setText(a);
        c2.setText(b);
        c3.setText(c);
        c4.setText(d);
        c5.setText(e);
        c6.setText(f);
      /* VerSimulacao ver = new VerSimulacao (a,b,c,d,e,f);
       
        ver.setVisible(true);
        this.dispose();
 */
    }//GEN-LAST:event_jButton1MouseClicked

    private void btn_desfazMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_desfazMouseClicked
      //cb_placa.removeAllItems();
        cb_process.removeAllItems();
        cb_mem.removeAllItems();
        cb_arm.removeAllItems();
        cb_fonte.removeAllItems();
        cb_pv.removeAllItems();      
         
        l1.setVisible(false);
        c1.setVisible(false);
        c2.setVisible(false);
        c3.setVisible(false);
        c4.setVisible(false);
        c5.setVisible(false);
        c6.setVisible(false);
        
        btn1.setEnabled(true);          
        btn2.setEnabled(true);
        btn3.setEnabled(true);
        btn4.setEnabled(true);
        btn5.setEnabled(true);
        btn6.setEnabled(true);

        cb_placa.setEnabled(true);
        cb_process.setEnabled(false);
        cb_mem.setEnabled(false);
        cb_fonte.setEnabled(false);
        cb_arm.setEnabled(false);
        cb_pv.setEnabled(false); 
        
    }//GEN-LAST:event_btn_desfazMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulacao().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn_desfaz;
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel c3;
    private javax.swing.JLabel c4;
    private javax.swing.JLabel c5;
    private javax.swing.JLabel c6;
    private javax.swing.JComboBox<MArmazenamento> cb_arm;
    private javax.swing.JComboBox<MFonte> cb_fonte;
    private javax.swing.JComboBox<MMemoria> cb_mem;
    private javax.swing.JComboBox<MPlacaMae> cb_placa;
    private javax.swing.JComboBox<MProcessador> cb_process;
    private javax.swing.JComboBox<MPlacavideo> cb_pv;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel l1;
    // End of variables declaration//GEN-END:variables
}
